### ISSUE TITLE
Small issues, and AttributeError:

### ISSUE THREAD

**Issue by Tiemichael** [peteS-UK/sonyavr#12]
I am running HA Version	core-2024.12.5, Installation type:	Home Assistant OS, unsing a STR-DN1060.

1) the port I have use is: 33335  (compared to 50001 in the Readme )
2) Even with the Sony OFF (power supply off), or in Network Standby - mode OFF, the Dashboard is blue, and says 'ON'. 
Maybe it's related to 
3) an error I see in my log-files:
`ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/sonyavr/media_player.py", line 99, in _async_startup
    await self._device.async_turn_on()
  File "/config/custom_components/sonyavr/sonyavr.py", line 1229, in async_turn_on
    await self.command_service.async_power_on()
  File "/config/custom_components/sonyavr/sonyavr.py", line 623, in async_power_on
    await self.async_send_command(CMD_POWER_ON)
  File "/config/custom_components/sonyavr/sonyavr.py", line 588, in async_send_command
    if not self.block_sending and self.command_writer is not None:
                                  ^^^^^^^^^^^^^^^^^^^
AttributeError: 'CommandService' object has no attribute 'command_writer'`

Thank you for your hard work in providing this integration!

**Comment by peteS-UK** [comment]
Hi.  Yes, that's basically saying the integration can't connect to the AVR - as if the port is wrong.  I took that port infor from another post (since there's nothing official out there) - what happens with 50001?  Since 1060 is an outlier with the port numbers, it's possible it's just different and might not work, but since there's no doc or API for any of this, it's always trial and error.

**Comment by Tiemichael** [comment]
Thanks for your quick reply!

I am using port 33335 also with an Android Remote (Anymote) - so it's the cirrect port for my DNS-1060.
Using port 50001 does not work  - the AVR shows no reaction at all.

Besides the isses I mentioned, the Integration is working fine.

If the AVR is connected to power (as a habit I switch off the power over night) the log-entry I mentioned as '3)' is gone.

What stays, is '2)' - although the AVR is OFF, it's reported as ON.

**Comment by peteS-UK** [comment]
OK - that's interesting.  Does the integration receive other feedback - get the volume etc.?  Could you send me debug logs.  With the avr in network standby, turn on debug logging on the integration, then reload the integration - under the 3 dots on the integration connection, and then post the log.  The link you've posted above just links back to this page for me btw - rather than to a log.

**Comment by Tiemichael** [comment]
Should be the right link now ...

[home-assistant_sonyavr_2024-12-29T10-03-23.333Z.log](https://github.com/user-attachments/files/18269071/home-assistant_sonyavr_2024-12-29T10-03-23.333Z.log)

**Comment by peteS-UK** [comment]
ok, so it's getting some feedback ok.  When you change the volume does the volume or source etc., does the volume change on the integration panel or sensor?  Just curious if it's only power.

Next question wil be, with debug logging on, turn the avr on and off.  Make a note of the times so I can see it in the log.  When you turn it on and off, does the display update - i.e. is the always on only when you first start, or does it always ignore the power state?

**Comment by Tiemichael** [comment]
Looking a little deeper: I cannot switch ON the AVR via HA,
Once the AVR is on, I can change the volume, input-source ... and also switch it OFF.
It seems that somewhere it's flaged as ON permanentely, so an switch ON command is ignored.
The last 4 lines in the attached log show my (not successful)  'switch ON' attempts.

[home-assistant_sonyavr_2024-12-29T10-56-51.342Z.log](https://github.com/user-attachments/files/18269210/home-assistant_sonyavr_2024-12-29T10-56-51.342Z.log)

**Comment by peteS-UK** [comment]
OK, so looks like the on command may be different perhaps.  With debug logging on, what do you see in the log if you turn on the AVR via the normal remote?

**Comment by Tiemichael** [comment]
when switching ON (via Wifi Remote CTL)
2024-12-29 19:12:46.853 INFO (MainThread) [custom_components.sonyavr.sonyavr] Debug b'02:07:a8:82:00:16:00:11:00'

when switching OFF (via HA)
2024-12-29 19:13:38.124 DEBUG (MainThread) [custom_components.sonyavr.sonyavr] Command : 0x2, 0x4, 0xa0, 0x60, 0x0, 0x0, 0x0
2024-12-29 19:13:38.416 INFO (MainThread) [custom_components.sonyavr.sonyavr] Debug b'02:07:a8:82:00:16:00:10:00'

**Comment by peteS-UK** [comment]
OK - it looks like the problem is the feedback on the power state is different, but I think the commands are thankfully ok.  I can post a beta to HACS.  BTW, when you say that volume and source work, do they updat ethe info in HA as well as sending the commands properly?  When you change the volume, does the volume sensor update?

**Comment by peteS-UK** [comment]
It looks to me like the volume feedback is different as well, so I'm expecting it not to work atm.  That's the Debug [unknown data packet]b'02:06:a8:8b:00:03:00:2a' entries in the log.  With you volume, what's the min and max.  does it run from 0 to 45, for example, or -80 to 20.

**Comment by Tiemichael** [comment]
Changing Source and Sound-mode via a Remote, is reflected correctly in the HA.
Changing Volume via Remote, does not show on the HA.
In the HA is see 2 ways the change the volume:  + / - Button is working, changing Volume via slider: not working.
My HA volume scale is 0 to 100, altough I have set it to 90 in the configuration.

If you want me to test some changes, I can directly do it in the .py-files.

Thanks!

**Comment by peteS-UK** [comment]
OK, that all makes sense.  I'll post a new version of sonysvr.py for you to test this afternoon - just going in the gym.  Should be fairly simple to fix I think.  Just need to try and make one version that covers all bases - i.e. these changes don't overlap with other feedback patterns frmo other avrs

**Comment by peteS-UK** [comment]
ok - give this a try.  I think the volume should work now, but the power is a bit of a guess...  The string like b'02:07:a8:82:00:16:00:11:00' is a combination of the source (02:07:a8:82:00:16) and then some other bytes showing the power status.  It can be off, (on & mute off), or (on and mute on).  With most of the other devices, the feedback for the power is different for each source, but I think these might be consistent across sources for you.  So, I think 02:07:a8:82:00:16:00:11:00 is satcatv source with power on mute off.  Then '02:07:a8:82:00:16:00:13:00' is power on mute on , and b'02:07:a8:82:00:16:00:10:00' is power off.  Try that, and see if it works with that source.  Then try turning mute on and off.  Then try other sources (muting on off).

[sonyavr.zip](https://github.com/user-attachments/files/18269876/sonyavr.zip)

**Comment by Tiemichael** [comment]
Thanks! I will test it tomorrow morning

**Comment by peteS-UK** [comment]
If something doesn't work as expected, just try and trap the debug message in the log for that particular action, and we should be able to work it out.  The overall structure all looks the same, but just some of the codes are different.

**Comment by Tiemichael** [comment]
Sorry for the delay ...
I manage to switch on the AVR via HA, but the ON-State seems not to be recognized.
As such it still is displayed as OFF, and no further control is possible, and it's also not possible to switch the AVR OFF.

**Comment by peteS-UK** [comment]
"Cannot disconnect from command socket" is it trying to reconnect which it looks like it did ok.  Might be worth power cycling the AVR when you restart HA to make sure things are clean while we play around - have it in network standby when you restart HA so things are clean.  Might be worth just clearing the logs as well each time as it's getting a bit long...

Here's a new version  - same code just with some more debug strings output.  Also, can you check volume as well - see if that's working now.

[sonyavr.zip](https://github.com/user-attachments/files/18272894/sonyavr.zip)

**Comment by peteS-UK** [comment]
actually, try this one - just decoded the debug data to make it easier to read
[sonyavr.zip](https://github.com/user-attachments/files/18273222/sonyavr.zip)

**Comment by Tiemichael** [comment]
Looking very good, but not yet perfect!
I have configured max Volume to 75 (the max number the AVR shows).
Via Remote Ctl or directly on the AVR I can adjust the volume between 0 and 75 (AVR scale), The slide on the HA 
SonyAVR integration shows a scale between 0 and 100, A volume of 100 on the HA, is a volume of 45 on the AVR. Not sure where the '75' is used...

The log is with the most recent version
[home-assistant_sonyavr_2024-12-30T08-54-28.743Z.log](https://github.com/user-attachments/files/18273289/home-assistant_sonyavr_2024-12-30T08-54-28.743Z.log)

**Comment by peteS-UK** [comment]
ok - there's a bug in the max volume changes - I overwrite the new max volume with a default when it reloads after I made another change to support a different proc a while back.  I'll fix that later.  What's happening with the on/off and debug with the latest version?

**Comment by Tiemichael** [comment]
ON/OFF seems fine as long as only the HA is used for control.
When I ON the AVR via a Remote Ctl, the status on the HA is not updated. Even after I switch OFF via Remote Ctl, the HA is unable to work. 
Most likely the only way to resolve this would be polling the ON/OFF state before any command, and even every 20sec or so....

I will try to prepare an according log-file later 

Thanks!

**Comment by peteS-UK** [comment]
No, that just means we haven't got the notification right yet.  When something changes on the avr, it sends out a notification.  We just need to trap that correctly - and they're different for each amp etc..  So, send me the debug with mute on and off when you press on from the remote..  Then, with the avr on and mute off, change the source using the knob on the avr, change it back the original source, mute on, change the source again,  With the latest version I posted an hour ago pls.  That debug should let us track down the codes.

**Comment by Tiemichael** [comment]
Sorry, I don't get your instructions ...
where do I press Mute/Unmute? on the AVR/Remote or the HA?
Do you want to use the Mute/Unmute notification to seperate between different commands or command from AVR/Remote vs HA?
Changing Sources and Sound Fields seem to the updated correctly

**Comment by peteS-UK** [comment]
Sorry, should have explained more.  Basically, the power and mute notifications are mixed together with the source notification.  So, there's no distinct notification for power state.  When you change the power, it sends a notification of source+mute_state+power_state.  There are 3 states for the second bit - power off, power on and muted, power on and unmuted.  When you change source, it'll send a notification which has the power and mute states as well.  The reason I want the source change with and without mute is that it's a distinct code for mute state+power state - e.g. there's not on byte that shows if it's muted and on and not-muted and on.  They're combined into a 3 byte notification on the end of the source notification.  

Make snese?

Easiest to make the changes on the AVR remote so that we can just see the feedback in HA.  So, each time you amke a change on the AVR remote, it'll send a notification to HA, which we can analyse.

**Comment by Tiemichael** [comment]
Ok ... hope I did it correctly (everything done with the AVR remote)

[home-assistant_sonyavr_2024-12-30T10-49-00.679Z.log](https://github.com/user-attachments/files/18274071/home-assistant_sonyavr_2024-12-30T10-49-00.679Z.log)

**Comment by peteS-UK** [comment]
Yes, that looks like the right idea, but that's not the latest .py file.  Did you maybe not reboot after copying it across - it only reloads the new code at reboot.

**Comment by Tiemichael** [comment]
Not sure what I did wrong ....
Here a new version:
[home-assistant_sonyavr_2024-12-30T11-25-32.508Z.log](https://github.com/user-attachments/files/18274299/home-assistant_sonyavr_2024-12-30T11-25-32.508Z.log)

**Comment by peteS-UK** [comment]
OK - here's a few new files which should fix the volume range problem with the slider, and that warning around unit of measurement that you might have seen and adds a bit more debug.

[sony.zip](https://github.com/user-attachments/files/18274653/sony.zip)

Thanks for the last log.  The integration seems to be receiving commands it understands ok.  When you use the avr remote to mute does HA also update its mute status?  Likewise for when you change power via the remote.  BTW, when you load a new version, HA sometimes seems to cache old things, so before you expect any updates after changing the integration, always best to hit cntl-r on the sonyavr integration settings page just to make it refresh (assuming you're running windows chrome/edge etc)

**Comment by Tiemichael** [comment]
Thanks!
Working almost perfectly!
After reloading the integration, the AVR was OFF, i did not notice an automatic ON/OFF-sequence, but the HA showed the AVR as ON. So I was not able to switch if ON from the HA.
After switching ON via the Remote everything was working fine.
Muting/Unmiting at the Remote is correctly shown at the HA.
The volume slider-scale is still showing 0 to 100, and changing the volume via the slider seems not working.

Maybe the log is helpful
[home-assistant_sonyavr_2024-12-30T13-09-46.818Z.log](https://github.com/user-attachments/files/18274891/home-assistant_sonyavr_2024-12-30T13-09-46.818Z.log)

**Comment by peteS-UK** [comment]
Yes, I can see that the AVR didn't respond to the initiation sequence.  That bit btw is to force the AVR to output its current state (source, volume etc.) when we startup else I don't know the starting values.  So, it turns on, mutes and unmutes, turns the volume up and down, changes the source up and down then turns off again.  With pauses in between, it takes about a minute to finish.  The AVR needs to be in network standby for any of that to work.  Could you maybe try putting the avr into standby and then rebooting HA to see what happens?

With the volume slider, it'll always show 0-100.  That's just the way HA displays volume (as a percentage).  The bit that should work now is that 100% equals 75, rather than 45.  Does changing the slider not do anything?

**Comment by peteS-UK** [comment]
BTW, in your test above, if you turned it off (via HA or remote), would HA turn it back on again?

**Comment by Tiemichael** [comment]
For my test yesterday when I rebooted the HA, the AVR was in Network Standby.
Trying again:  
- restarting the HA: Startup-sequence is running
- rebooting the HA: Startup-sequence is running
- the Volume-sliders are working
- turning ON/OFF via Remote and OFF/On via HA, is working in all cases.
[home-assistant_sonyavr_2024-12-31T03-00-59.797Z.log](https://github.com/user-attachments/files/18278975/home-assistant_sonyavr_2024-12-31T03-00-59.797Z.log)

There might be some cases where the HA integration hangs or is in a wrong state, but I did not encounter it today.

Thank you for your hard work and support!

**Comment by peteS-UK** [comment]
So, am I right in reading that on/off from HA did work, and then after some time just stopped working?  I assume nothing changed on the AVR side in that time?  I know you said you turned the AVR off at night, but this all looks` like daytime.  Actually, I don't think this will reconnect correctly if you did turn the AVR off....  

At the end of the log, I see ....

`2024-12-31 16:44:59.945 INFO (MainThread) [custom_components.sonyavr.sonyavr] Debug b'02:07:a8:82:00:16:00:11:00'
2024-12-31 16:48:05.391 INFO (MainThread) [custom_components.sonyavr.sonyavr] Debug b'02:07:a8:82:00:16:00:10:00'
2024-12-31 16:48:43.681 ERROR (MainThread) [custom_components.sonyavr.sonyavr] Send command failed.  Attempting to reconnect
2024-12-31 16:48:43.682 ERROR (MainThread) [custom_components.sonyavr.sonyavr] Cannot disconnect from command socket
2024-12-31 16:49:52.231 INFO (MainThread) [custom_components.hacs] Loading known repositories
2024-12-31 16:59:39.648 DEBUG (MainThread) [custom_components.sonyavr.sonyavr] Command : 0x2, 0x4, 0xa0, 0x60, 0x0, 0x1, 0x0
2024-12-31 17:00:13.737 DEBUG (MainThread) [custom_components.sonyavr.sonyavr] Command : 0x2, 0x4, 0xa0, 0x60, 0x0, 0x1, 0x0`

That looks like you turning it on and off via the remote, then trying to do something via HA which then failed and then sending turn on several times, with no response.  It looks like it's lost the network connection to the AVR, hence the reconnect required.  I've never seen that with mine tbh.  But, if it looses the network connection intermittently, then it would also loose the listener for the feedback, which isn't restarted.  I can try and add a reconnect for the listener if the send command fails, but that won't help with feedback if you're changing the state via the remote and it's lost the connection.  

Underlying question thogh is why is it loosing the connection to the avr.  Are you aware of any underlying problems?

I also see that long running task on startup that I don't see on mine.  I'll move that to a background task, but it's odd that you get that warning and I don't - probably a combination of evrerything else going on a startup.  That might be wht the startup initialistion didn't run for you sometimes.

**Comment by Tiemichael** [comment]
The problem started (if I recall correclty), when switching the AVR ON,  and OFF  too early - before the ON was finished (e.g the AVR has not yet sent out some status-update). So maybe some internal state in got corrupted.
My AVR is connected to the router via LAN, with a static IP. I am not aware of any issues, but I am going to monitor the connection.
The Log-Erros 'WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_default_certs with args' are related to my Aircon
The Log-errors 'ERROR (MainThread) [aiohttp.server] Error handling request' are realted to a Smart TV (which was OFF at that time),
I also realize that restarting the HA takes 10-20sec, but rebooting takes about 5 min ... need to investigate.

Thanks!

**Comment by peteS-UK** [comment]
I do think there's something unusual, or at least different, going on.  The disconnect you're seeing shouldn't really be happening, and I've never seen it tbh.  Also, that startup delay is odd - again I haven't seen that or had it reported, and I think it's only happening because something else is delaying things.  Anyway, this version of media_player moves the initialisation step to after HA has finished startup, and spins it off as its own task, so shouldn't interfere or be interfered with by anything.  Having said that, you'll definately need to wait for it to finish before doing anything - the end of the init is when the AVR turns itself off again.

[media_player.zip](https://github.com/user-attachments/files/18282906/media_player.zip)

**Comment by Tiemichael** [comment]
Great! Thank you!
Currentyl I do ot see any issues with ON/OFF-status, volume .... Everything look good!
The other issues(startup-delay, disconnect) I have to investigate further

**Comment by peteS-UK** [comment]
OK, if you're happy shall we close this issue down now and feel free to open any new issues?  I'll take out some of the extra debug strings and post a new release.

**Comment by Tiemichael** [comment]
Thank you for your outstanding support,
highly appreciated!

**Comment by peteS-UK** [comment]
No problem.  Glad we got it working.  I've posted the release as v1.5.0 to HACS now.
